import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ingot, IngotWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Configure mock adapters for production (until Forge/Anvil are integrated)
# When ready for real integration, switch to ElixirAdapter:
# config :ingot,
#   forge_client_adapter: Ingot.ForgeClient.ElixirAdapter,
#   anvil_client_adapter: Ingot.AnvilClient.ElixirAdapter
config :ingot,
  forge_client_adapter: Ingot.ForgeClient.MockAdapter,
  anvil_client_adapter: Ingot.AnvilClient.MockAdapter

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
